language: python
python:
- '2.6'
- '2.7'
addons:
  firefox: '31.0'
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile
  --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16
install:
- npm install
- npm install -g grunt-cli
script:
- python python-packages/fle_utils/tests.py
- python kalite/manage.py syncdb --migrate --noinput --traceback
- python kalite/manage.py test
- grunt jshint
notifications:
  email:
  - aron@learningequality.org
  - jamie@learningequality.org
  hipchat:
    rooms:
      secure: SnwCQIhrG/BVDUHtPDxfTFDytwuHcrIFQKhgy9jrM7MHIDVsGgQvd388v62upwHVCKONMrvW5qIYAjd7dZWPmO+A4nOLYrTv+JTYsmyMUVka1j9IgApqMTexfpDlM08CsZjbK0HPZuhBylcfIDSFu2NWDT8O/vIa7rwKUafKWBw=
      template:
        - '%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}'